"""Public API for Recruiter Document Truth Validation (FR-014).

M1: typed contracts.
M2: catalogue + technology detection/validation.
M3: persistence, owner CLI, package/submission external-use gates.
"""

from __future__ import annotations

from .aliases import WELL_KNOWN_TECHNOLOGY_LABELS, alias_keys_for, expand_alias_labels
from .catalogue import (
    AI_ENGINEERING_DURATION_KEY,
    COMMERCIAL_AI_KEY,
    COMMERCIAL_SOFTWARE_KEY,
    INDEPENDENT_ENGINEERING_KEY,
    SOFTWARE_ENGINEERING_DURATION_KEY,
    build_catalogue_from_profile,
    catalogue_entry_by_key,
    catalogue_supports_kind,
    catalogue_supports_technology,
)
from .contracts import (
    expected_minimum_severity_for_finding,
    validate_catalogue_contract,
    validate_truth_report_contract,
)
from .detection import (
    DetectedTechnologySpan,
    build_technology_lexicon,
    detect_technology_claims,
    detect_technology_spans,
    technology_supported,
)
from .extended_claims import (
    WELL_KNOWN_CERTIFICATIONS,
    WELL_KNOWN_DOMAINS,
    DetectedExtendedSpan,
    detect_extended_claims,
    detect_extended_spans,
)
from .errors import ErrorDetail, TruthContractError, TruthSchemaError, TruthValidationError
from .gates import (
    DocumentTruthStatus,
    PackageTruthStatus,
    TruthGateError,
    evaluate_package_truth,
    evaluate_report_for_external_use,
    require_package_external_use,
)
from .hashing import hashes_match, markdown_content_hash, read_markdown
from .ids import (
    new_catalogue_entry_id,
    new_claim_id,
    new_truth_finding_id,
    new_truth_report_id,
)
from .models import (
    CANDIDATE_AUTHORITATIVE_SOURCES,
    CLAIM_CLASSES,
    CLAIM_KINDS,
    CLAIM_STRENGTHS,
    CONTEXT_ONLY_SOURCES,
    COVERAGE_STATUSES,
    DETECTION_CERTAINTIES,
    EVIDENCE_AUTHORITIES,
    EVIDENCE_SOURCE_KINDS,
    EVIDENCE_STATUSES,
    FINDING_SEVERITIES,
    HIGH_CLAIM_STRENGTHS,
    TRUTH_OUTCOMES,
    VALIDATOR_VERSION,
    ArtefactKind,
    ArtefactRef,
    CandidateEvidenceCatalogue,
    CatalogueEntryId,
    CatalogueEvidenceEntry,
    Claim,
    ClaimClass,
    ClaimId,
    ClaimKind,
    ClaimStrength,
    ClaimSubject,
    CoverageStatus,
    DetectionCertainty,
    EvidenceAuthority,
    EvidenceProvenance,
    EvidenceSourceKind,
    EvidenceStatus,
    FindingSeverity,
    TruthFinding,
    TruthFindingId,
    TruthOutcome,
    TruthReport,
    TruthReportId,
    ValidationGate,
)
from .normalise import display_label, normalise_object_key
from .service import TruthValidationService
from .store import (
    DEFAULT_TRUTH_REPORTS_ROOT,
    JsonDirectoryTruthReportStore,
    TruthReportNotFoundError,
)

__all__ = [
    "CANDIDATE_AUTHORITATIVE_SOURCES",
    "CLAIM_CLASSES",
    "CLAIM_KINDS",
    "CLAIM_STRENGTHS",
    "CONTEXT_ONLY_SOURCES",
    "COVERAGE_STATUSES",
    "DEFAULT_TRUTH_REPORTS_ROOT",
    "DETECTION_CERTAINTIES",
    "EVIDENCE_AUTHORITIES",
    "EVIDENCE_SOURCE_KINDS",
    "EVIDENCE_STATUSES",
    "FINDING_SEVERITIES",
    "HIGH_CLAIM_STRENGTHS",
    "TRUTH_OUTCOMES",
    "VALIDATOR_VERSION",
    "WELL_KNOWN_CERTIFICATIONS",
    "WELL_KNOWN_DOMAINS",
    "WELL_KNOWN_TECHNOLOGY_LABELS",
    "ArtefactKind",
    "ArtefactRef",
    "CandidateEvidenceCatalogue",
    "CatalogueEntryId",
    "CatalogueEvidenceEntry",
    "Claim",
    "ClaimClass",
    "ClaimId",
    "ClaimKind",
    "ClaimStrength",
    "ClaimSubject",
    "CoverageStatus",
    "DetectedTechnologySpan",
    "DetectedExtendedSpan",
    "DetectionCertainty",
    "DocumentTruthStatus",
    "ErrorDetail",
    "EvidenceAuthority",
    "EvidenceProvenance",
    "EvidenceSourceKind",
    "EvidenceStatus",
    "FindingSeverity",
    "JsonDirectoryTruthReportStore",
    "PackageTruthStatus",
    "TruthContractError",
    "TruthFinding",
    "TruthFindingId",
    "TruthGateError",
    "TruthOutcome",
    "TruthReport",
    "TruthReportId",
    "TruthReportNotFoundError",
    "TruthSchemaError",
    "TruthValidationError",
    "TruthValidationService",
    "ValidationGate",
    "alias_keys_for",
    "build_catalogue_from_profile",
    "build_technology_lexicon",
    "catalogue_entry_by_key",
    "catalogue_supports_kind",
    "catalogue_supports_technology",
    "COMMERCIAL_AI_KEY",
    "COMMERCIAL_SOFTWARE_KEY",
    "INDEPENDENT_ENGINEERING_KEY",
    "SOFTWARE_ENGINEERING_DURATION_KEY",
    "AI_ENGINEERING_DURATION_KEY",
    "detect_extended_claims",
    "detect_extended_spans",
    "detect_technology_claims",
    "detect_technology_spans",
    "display_label",
    "evaluate_package_truth",
    "evaluate_report_for_external_use",
    "expand_alias_labels",
    "expected_minimum_severity_for_finding",
    "hashes_match",
    "markdown_content_hash",
    "new_catalogue_entry_id",
    "new_claim_id",
    "new_truth_finding_id",
    "new_truth_report_id",
    "normalise_object_key",
    "read_markdown",
    "require_package_external_use",
    "technology_supported",
    "validate_catalogue_contract",
    "validate_truth_report_contract",
]
