"""Public API for FR-016 multi-agent orchestration (M1–M4; Complete / Frozen).

Learning proof only — prefer ``cic agent run`` for ordinary preparation.

FR-017 M1 adds derive-only observability helpers under ``.observability``
(no DOS/BOPA/OBS/runtime behaviour changes).
"""

from __future__ import annotations

from .bopa_adapter import BopaSpecialistAdapter, BopaSpecialistResult
from .briefing import (
    approved_specialists_for,
    classify_briefing_needs,
    obs_adds_value_beyond_bopa,
    primary_briefing_need,
    recommended_next_step_from_observation,
    select_next_specialist,
)
from .contracts import (
    assert_obs_cannot_mutate,
    validate_delegation_proposal_contract,
    validate_handoff_contract,
    validate_operational_brief_contract,
    validate_orchestration_run_contract,
)
from .delegation_policy import (
    evaluate_delegation_policy,
    handoff_idempotency_key,
    require_delegation_allowed,
)
from .errors import (
    DelegationPolicyError,
    DomainWorkForbiddenError,
    MultiAgentContractError,
    ObsPolicyError,
    OrchestrationRunNotFoundError,
    OrchestrationRuntimeError,
    OrchestrationStorageError,
)
from .evaluation import CorpusCaseResult, CorpusReport, go_no_go_assessment, run_corpus
from .factory import build_orchestration_supervisor
from .goals import (
    OWNER_ORCHESTRATION_GOALS,
    OwnerOrchestrationGoalName,
    goal_from_owner_name,
    owner_goal_label,
)
from .hashing import compute_observation_hash
from .ids import (
    new_handoff_id,
    new_operational_brief_id,
    new_orchestration_audit_event_id,
    new_orchestration_run_id,
)
from .json_store import DEFAULT_ORCHESTRATION_RUNS_ROOT, JsonDirectoryOrchestrationStore
from .memory_store import InMemoryOrchestrationStore
from .models import (
    DelegationDecision,
    Handoff,
    HandoffId,
    ObsActionProposal,
    ObsPolicyDecision,
    OperationalBrief,
    OperationalBriefId,
    OrchestrationAuditEvent,
    OrchestrationAuditEventId,
    OrchestrationGoal,
    OrchestrationObservation,
    OrchestrationRun,
    OrchestrationRunId,
    SpecialistDelegationProposal,
    SpecialistVisitRecord,
)
from .observation import (
    ObservationBuilder,
    ReadinessObservationBuilder,
    StaticObservationBuilder,
    observation_from_snapshot,
)
from .observability import (
    RECONSTRUCTABILITY_IDS,
    RECONSTRUCTABILITY_QUESTIONS,
    HandoffMetrics,
    OrchestrationCorpusMetrics,
    OrchestrationRunMetrics,
    ParentChildCorrelation,
    ReconstructabilityCheck,
    ReconstructabilityId,
    ReconstructabilityReport,
    SpecialistVisitMetrics,
    aggregate_orchestration_metrics,
    correlate_parent_child,
    evaluate_reconstructability,
    extract_handoff_metrics,
    extract_orchestration_run_metrics,
)
from .observability_corpus import (
    CORPUS_CASE_IDS,
    ObservabilityCaseResult,
    ObservabilityCorpusReport,
    ObservabilityFixture,
    get_demo_fixture,
    go_no_go_observability,
    list_demo_fixture_ids,
    run_observability_corpus,
)
from .observability_presentation import (
    evaluate_run_observability,
    format_corpus_cli,
    format_corpus_observability_report,
    format_fixture_observability,
    format_observability_report,
    format_store_observability,
    load_child_agent_metrics,
    load_handoffs_for_run,
)
from .obs_policy import (
    approved_obs_actions_for,
    evaluate_obs_action_policy,
    require_obs_action_allowed,
)
from .obs_runtime import ObsRuntime
from .presentation import (
    format_orchestration_history,
    format_orchestration_list_line,
    format_orchestration_report,
    owner_action_for_orchestration,
    specialist_authority_lines,
)
from .specialist_registry import (
    BOPA_SPECIALIST,
    OBS_SPECIALIST,
    SPECIALIST_REGISTRY,
    get_specialist,
    is_future_placeholder,
    specialist_may_mutate,
)
from .supervisor import DeterministicOrchestrationSupervisor
from .types import (
    BRIEFING_NEED_CLASSES,
    DEFAULT_MAX_OBS_STEPS,
    DEFAULT_MAX_ORCHESTRATION_STEPS,
    DEFAULT_MAX_VISITS_PER_SPECIALIST,
    DELEGATION_DECISION_KINDS,
    FUTURE_SPECIALIST_IDS,
    HANDOFF_ACCEPTANCES,
    OBS_ACTIONS,
    OBS_FORBIDDEN_ACTION_NAMES,
    ORCHESTRATION_AUDIT_EVENT_KINDS,
    ORCHESTRATION_GOAL_KINDS,
    ORCHESTRATION_RUN_STATUSES,
    ORCHESTRATION_STOP_REASONS,
    RECOMMENDED_NEXT_STEPS,
    SPECIALIST_IDS,
    BriefingNeedClass,
    DelegationDecisionKind,
    HandoffAcceptance,
    ObsAction,
    OrchestrationAuditEventKind,
    OrchestrationGoalKind,
    OrchestrationRunStatus,
    OrchestrationStopReason,
    RecommendedNextStep,
    SpecialistId,
)
__all__ = [
    "BOPA_SPECIALIST",
    "BRIEFING_NEED_CLASSES",
    "BopaSpecialistAdapter",
    "BopaSpecialistResult",
    "CorpusCaseResult",
    "CorpusReport",
    "CORPUS_CASE_IDS",
    "DEFAULT_MAX_OBS_STEPS",
    "DEFAULT_MAX_ORCHESTRATION_STEPS",
    "DEFAULT_MAX_VISITS_PER_SPECIALIST",
    "DEFAULT_ORCHESTRATION_RUNS_ROOT",
    "DELEGATION_DECISION_KINDS",
    "DeterministicOrchestrationSupervisor",
    "DomainWorkForbiddenError",
    "FUTURE_SPECIALIST_IDS",
    "HANDOFF_ACCEPTANCES",
    "HandoffMetrics",
    "InMemoryOrchestrationStore",
    "JsonDirectoryOrchestrationStore",
    "OBS_ACTIONS",
    "OBS_FORBIDDEN_ACTION_NAMES",
    "OBS_SPECIALIST",
    "ORCHESTRATION_AUDIT_EVENT_KINDS",
    "ORCHESTRATION_GOAL_KINDS",
    "ORCHESTRATION_RUN_STATUSES",
    "ORCHESTRATION_STOP_REASONS",
    "OWNER_ORCHESTRATION_GOALS",
    "ObsRuntime",
    "ObservationBuilder",
    "ObservabilityCaseResult",
    "ObservabilityCorpusReport",
    "ObservabilityFixture",
    "OrchestrationCorpusMetrics",
    "OrchestrationRunMetrics",
    "OwnerOrchestrationGoalName",
    "ParentChildCorrelation",
    "RECOMMENDED_NEXT_STEPS",
    "RECONSTRUCTABILITY_IDS",
    "RECONSTRUCTABILITY_QUESTIONS",
    "ReadinessObservationBuilder",
    "ReconstructabilityCheck",
    "ReconstructabilityId",
    "ReconstructabilityReport",
    "SPECIALIST_IDS",
    "SPECIALIST_REGISTRY",
    "StaticObservationBuilder",
    "SpecialistVisitMetrics",
    "BriefingNeedClass",
    "DelegationDecision",
    "DelegationDecisionKind",
    "DelegationPolicyError",
    "Handoff",
    "HandoffAcceptance",
    "HandoffId",
    "MultiAgentContractError",
    "ObsAction",
    "ObsActionProposal",
    "ObsPolicyDecision",
    "ObsPolicyError",
    "OperationalBrief",
    "OperationalBriefId",
    "OrchestrationAuditEvent",
    "OrchestrationAuditEventId",
    "OrchestrationAuditEventKind",
    "OrchestrationGoal",
    "OrchestrationGoalKind",
    "OrchestrationObservation",
    "OrchestrationRun",
    "OrchestrationRunId",
    "OrchestrationRunNotFoundError",
    "OrchestrationRunStatus",
    "OrchestrationRuntimeError",
    "OrchestrationStopReason",
    "OrchestrationStorageError",
    "RecommendedNextStep",
    "SpecialistDelegationProposal",
    "SpecialistId",
    "SpecialistVisitRecord",
    "aggregate_orchestration_metrics",
    "approved_obs_actions_for",
    "approved_specialists_for",
    "assert_obs_cannot_mutate",
    "build_orchestration_supervisor",
    "classify_briefing_needs",
    "compute_observation_hash",
    "correlate_parent_child",
    "evaluate_delegation_policy",
    "evaluate_obs_action_policy",
    "evaluate_reconstructability",
    "extract_handoff_metrics",
    "extract_orchestration_run_metrics",
    "format_corpus_cli",
    "format_corpus_observability_report",
    "format_fixture_observability",
    "format_observability_report",
    "format_orchestration_history",
    "format_orchestration_list_line",
    "format_orchestration_report",
    "format_store_observability",
    "get_demo_fixture",
    "get_specialist",
    "go_no_go_assessment",
    "go_no_go_observability",
    "goal_from_owner_name",
    "handoff_idempotency_key",
    "is_future_placeholder",
    "list_demo_fixture_ids",
    "load_child_agent_metrics",
    "load_handoffs_for_run",
    "evaluate_run_observability",
    "new_handoff_id",
    "new_operational_brief_id",
    "new_orchestration_audit_event_id",
    "new_orchestration_run_id",
    "obs_adds_value_beyond_bopa",
    "observation_from_snapshot",
    "owner_action_for_orchestration",
    "owner_goal_label",
    "primary_briefing_need",
    "recommended_next_step_from_observation",
    "require_delegation_allowed",
    "require_obs_action_allowed",
    "run_corpus",
    "run_observability_corpus",
    "select_next_specialist",
    "specialist_authority_lines",
    "specialist_may_mutate",
    "validate_delegation_proposal_contract",
    "validate_handoff_contract",
    "validate_operational_brief_contract",
    "validate_orchestration_run_contract",
]
