"""Public API for durable Opportunity persistence (M1–M3, FR-009)."""

from .bridge import OpportunityCsvBridge
from .csv_export import DEFAULT_EXPORT_PATH, EXPORT_COLUMNS, OpportunityCsvExporter
from .duplicate_service import DuplicateReviewService
from .errors import (
    ErrorDetail,
    OpportunityArtifactExistsError,
    OpportunityError,
    OpportunityNotFoundError,
    OpportunityStorageError,
    OpportunityTransitionError,
    OpportunityValidationError,
)
from .identity import new_opportunity_id
from .legacy_import import (
    LEGACY_OUTCOME_MAP,
    LEGACY_STATUS_MAP,
    LegacyImportReport,
    LegacyOpportunityCsvImporter,
    LegacyRowResult,
)
from .models import (
    ARTIFACT_FILENAMES,
    DUPLICATE_EVIDENCE_KINDS,
    INTERVIEW_STAGES,
    OUTCOME_KINDS,
    OWNER_DECISION_KINDS,
    PIPELINE_STATUSES,
    REVIEW_ACTION_KINDS,
    TERMINAL_STATUSES,
    DuplicateEvidenceKind,
    DuplicateRejection,
    DuplicateRelation,
    LegacyImportProvenance,
    Opportunity,
    OpportunityIdentity,
    OpportunityReview,
    OutcomeKind,
    OutcomeRecord,
    OwnerDecisionKind,
    OwnerDecisionRecord,
    PipelineStatus,
    ReviewActionKind,
    ReviewActionRecord,
    SourceKind,
    StrategySummary,
)
from .review_service import OpportunityReviewService
from .service import OpportunityArtifacts, OpportunityService

__all__ = [
    "ARTIFACT_FILENAMES",
    "DEFAULT_EXPORT_PATH",
    "DUPLICATE_EVIDENCE_KINDS",
    "EXPORT_COLUMNS",
    "DuplicateEvidenceKind",
    "DuplicateRejection",
    "DuplicateRelation",
    "DuplicateReviewService",
    "ErrorDetail",
    "INTERVIEW_STAGES",
    "LEGACY_OUTCOME_MAP",
    "LEGACY_STATUS_MAP",
    "LegacyImportProvenance",
    "LegacyImportReport",
    "LegacyOpportunityCsvImporter",
    "LegacyRowResult",
    "OUTCOME_KINDS",
    "OWNER_DECISION_KINDS",
    "PIPELINE_STATUSES",
    "REVIEW_ACTION_KINDS",
    "TERMINAL_STATUSES",
    "Opportunity",
    "OpportunityArtifactExistsError",
    "OpportunityArtifacts",
    "OpportunityCsvBridge",
    "OpportunityCsvExporter",
    "OpportunityError",
    "OpportunityIdentity",
    "OpportunityNotFoundError",
    "OpportunityReview",
    "OpportunityReviewService",
    "OpportunityService",
    "OpportunityStorageError",
    "OpportunityTransitionError",
    "OpportunityValidationError",
    "OutcomeKind",
    "OutcomeRecord",
    "OwnerDecisionKind",
    "OwnerDecisionRecord",
    "PipelineStatus",
    "ReviewActionKind",
    "ReviewActionRecord",
    "SourceKind",
    "StrategySummary",
    "new_opportunity_id",
]
